package com.tarang.dpq2.base.jpos_class;

public interface ConstantApp {

//checking sub transaction  condition and  set  value from ConstantValue

    String AUTH = "AUTH";
    String AUTHORIZATION_ADVICE = "AUTHORIZATION_ADVICE";
    String AUTH_ADVISE = "AUTH_ADVISE";
    String AUTH_ADVISE_REPEAT = "AUTH_ADVISE_REPEAT";
    String FINANCIAL = "FINANCIAL";
    String FINANCIAL_ADVISE = "FINANCIAL_ADVISE";
    String FINANCIAL_ADVISE_REPEAT = "FINANCIAL_ADVISE_REPEAT";
    String FILEACTION = "FILEACTION";
    String FILEACTION_REPEAT = "FILEACTION_REPEAT";
    String REVERSAL = "REVERSAL";
    String REVERSAL_REPEAT = "REVERSAL_REPEAT";
    //    String RECONCILIATION = "RECONCILIATION";
    String RECONCILIATION_REPEAT = "RECONCILIATION_REPEAT";
    String ADMIN_NOTIFICATION = "ADMIN_NOTIFICATION";
    String NETWORK_MNGMT = "NETWORK_MNGMT";
    String OFFLINE_PURCHASE = "OFFLINE_PURCHASE";

    //setting value process code

    //for debit

    String NOTXN_DEBIT = "NOTXN_DEBIT";
    String PURCHASE_DEBIT = "PURCHASE_DEBIT";
    String PURCHASE_CASHBACK_DEBIT = "PURCHASE_CASHBACK_DEBIT";
    String PURCHASE_REVERSAL_DEBIT = "PURCHASE_REVERSAL_DEBIT";
    String CASH_ADVANCE_DEBIT = "CASH_ADVANCE_DEBIT";
    String REFUND_DEBIT = "REFUND_DEBIT";
    String PRE_AUTHORISATION_DEBIT = "PRE_AUTHORISATION_DEBIT";
    String PURCHASE_ADVICE_DEBIT = "PURCHASE_ADVICE_DEBIT";
    String PRE_AUTHORISATION_COMPLET_DEBIT = "PRE_AUTHORISATION_COMPLET_DEBIT";
    String RECONCILIATION_TXN_DEBIT = "RECONCILIATION_TXN_DEBIT";
    String NETWORK_MNGMT_TXN_DEBIT = "NETWORK_MNGMT_TXN_DEBIT";
    String FILEACTION_TXN_DEBIT = "FILEACTION_TXN_DEBIT";
    String ADMIN_NOTIFICATION_TXN_DEBIT = "ADMIN_NOTIFICATION_TXN_DEBIT";
    String OFFLINE_DEBIT = "OFFLINE_DEBIT";
    String SETTLEMENT_DEBIT = "SETTLEMENT_DEBIT";
    String BATCH_UPLOAD_DEBIT = "BATCH_UPLOAD_DEBIT";
    String SETTLEMENT_CLOSURE_DEBIT = "SETTLEMENT_CLOSURE_DEBIT";
    String SUMMARY_RPT_DEBIT = "SUMMARY_RPT_DEBIT";
    String REPRINT_LAST_TXN_DEBIT = "REPRINT_LAST_TXN_DEBIT";
    String SNAPSHOT_BALANCE_DEBIT = "SNAPSHOT_BALANCE_DEBIT";
    String RUNNING_BALANCE_DEBIT = "RUNNING_BALANCE_DEBIT";
    String FULLDOWNLOAD_DEBIT = "FULLDOWNLOAD_DEBIT";
    String PARTIALDOWNLOAD_DEBIT = "PARTIALDOWNLOAD_DEBIT";
    String NO_OF_TXNS_DEBIT = "NO_OF_TXNS_DEBIT";

    //for credit

    String NOTXN_CREDIT = "NOTXN_CREDIT";
    String PURCHASE_CREDIT = "PURCHASE_CREDIT";
    String PURCHASE_CASHBACK_CREDIT = "PURCHASE_CASHBACK_CREDIT";
    String PURCHASE_REVERSAL_CREDIT = "PURCHASE_REVERSAL_CREDIT";
    String CASH_ADVANCE_CREDIT = "CASH_ADVANCE_CREDIT";
    String REFUND_CREDIT = "REFUND_CREDIT";
    String PRE_AUTHORISATION_CREDIT = "PRE_AUTHORISATION_CREDIT";
    String PURCHASE_ADVICE_CREDIT = "PURCHASE_ADVICE_CREDIT";
    String PRE_AUTHORISATION_COMPLET_CREDIT = "PRE_AUTHORISATION_COMPLET_CREDIT";
    String RECONCILIATION_TXN_CREDIT = "RECONCILIATION_TXN_CREDIT";
    String NETWORK_MNGMT_TXN_CREDIT = "NETWORK_MNGMT_TXN_CREDIT";
    String FILEACTION_TXN_CREDIT = "FILEACTION_TXN_CREDIT";
    String ADMIN_NOTIFICATION_TXN_CREDIT = "ADMIN_NOTIFICATION_TXN_CREDIT";
    String OFFLINE_CREDIT = "OFFLINE_CREDIT";
    String SETTLEMENT_CREDIT = "SETTLEMENT_CREDIT";
    String BATCH_UPLOAD_CREDIT = "BATCH_UPLOAD_CREDIT";
    String SETTLEMENT_CLOSURE_CREDIT = "SETTLEMENT_CLOSURE_CREDIT";
    String SUMMARY_RPT_CREDIT = "SUMMARY_RPT_CREDIT";
    String REPRINT_LAST_TXN_CREDIT = "REPRINT_LAST_TXN_CREDIT";
    String SNAPSHOT_BALANCE_CREDIT = "SNAPSHOT_BALANCE_CREDIT";
    String RUNNING_BALANCE_CREDIT = "RUNNING_BALANCE_CREDIT";
    String FULLDOWNLOAD_CREDIT = "FULLDOWNLOAD_CREDIT";
    String PARTIALDOWNLOAD_CREDIT = "PARTIALDOWNLOAD_CREDIT";
    String NO_OF_TXNS_CREDIT = "NO_OF_TXNS_CREDIT";

    //setting value for function code

    String AMOUNT_ACCURATE = "AMOUNT_ACCURATE";
    String AMOUNT_ESTIMATE = "AMOUNT_ESTIMATE";
    String PREAUTH_INITIAL_COMPLETION = "PREAUTH_INITIAL_COMPLETION";
    String AUTHORIZATION_EXTENSION = "AUTHORIZATION_EXTENSION";
    String ORIGIN_FINANCIAL_REQ_ADV = "ORIGIN_FINANCIAL_REQ_ADV";
    String APPROVED_AUTH_SAME_AMOUNT = "APPROVED_AUTH_SAME_AMOUNT";
    String APPROVED_AUTH_DIFF_AMOUNT = "APPROVED_AUTH_DIFF_AMOUNT";
    String REPLACE_FIELDS_RECORD = "REPLACE_FIELDS_RECORD";
    String REPLACE_ENTIRE_RECORD = "REPLACE_ENTIRE_RECORD";
    String REPLACE_FILE = "REPLACE_FILE";
    String TXN_NOT_COMPLETED = "TXN_NOT_COMPLETED";
    String TERMINAL_RECONCILIATION = "TERMINAL_RECONCILIATION";
    String FORCE_RECONCILIATION = "FORCE_RECONCILIATION";
    String UNABLE_PARSE_MSG = "UNABLE_PARSE_MSG";
    String MAC_ERROR = "MAC_ERROR";
    String TERMINAL_REGISTRATION = "TERMINAL_REGISTRATION";

    //setting value for function code
    String TERMINAL_PROCESSED = "TERMINAL_PROCESSED";
    String ICC_PROCESSED = "ICC_PROCESSED";
    String UNDER_FLOOR_LIMIT = "UNDER_FLOOR_LIMIT";
    String ICC_RANDOM_SEL = "ICC_RANDOM_SEL";
    String TER_RANDOM_SEL = "TER_RANDOM_SEL";
    String ONLINE_ICC = "ONLINE_ICC";
    String ONLINE_CARD_ACCEPTOR = "ONLINE_CARD_ACCEPTOR";
    String ONLINE_TERMINAL = "ONLINE_TERMINAL";
    String ONLINE_CARD_ISSUER = "ONLINE_CARD_ISSUER";
    String MERCHANT_SUSPICIOUS = "MERCHANT_SUSPICIOUS";
    String FALLBACK_ICCTOMSR = "FALLBACK_ICCTOMSR";
    String CLESS_TXN = "CLESS_TXN";
    String CLESS_TXN_ADVICE = "CLESS_TXN_ADVICE";
    String CUSTOMER_CANCELLATION = "CUSTOMER_CANCELLATION";
    String UNSPECIFIED = "UNSPECIFIED";
    String SUSPECTED_MALFUNC = "SUSPECTED_MALFUNC";
    String FORMAT_ERROR = "FORMAT_ERROR";
    String INCORRECT_AMOUNT = "INCORRECT_AMOUNT";
    String RES_RECEIVED_LATE = "RES_RECEIVED_LATE";
    String UNABLE_COMPLETE_TXN = "UNABLE_COMPLETE_TXN";
    String UNABLE_DELIVER_MSG = "UNABLE_DELIVER_MSG";
    String INVALID_RESP = "INVALID_RESP";
    String TIMEOUT_WAITING_RESP = "TIMEOUT_WAITING_RESP";
    String MAC_FAILURE = "MAC_FAILURE";


    //isoPackettype
    String ISO_PACKET_TYPE = "ISO_PACKET_TYPE";
    String TRANSACTION = "TRANSACTION";
    //includes =====>fileaction, network registration, RECONCILIATION..... already defined

    //Transaction Type's
    String PURCHASE = "PURCHASE";
    String NAQD_AMOUNT = "NAQD_AMOUNT";
    String PURCHASE_REVERSAL = "PURCHASE_REVERSAL";
    String REFUND = "REFUND";
    String CASH_ADVANCE = "CASH_ADVANCE";
    String PRE_AUTHORISATION = "PRE_AUTHORISATION";
    String PRE_AUTHORISATION_VOID = "PRE_AUTHORISATION_VOID";
    String PRE_AUTHORISATION_VOID_FULL = "PRE_AUTHORISATION_VOID_FULL";
    String PRE_AUTHORISATION_VOID_PARTIAL = "PRE_AUTHORISATION_VOID_PARTIAL";
    String PRE_AUTHORISATION_EXTENSION = "PRE_AUTHORISATION_EXTENSTION";
    String PURCHASE_ADVICE = "PURCHASE_ADVICE";
    String PURCHASE_ADVICE_FULL = "PURCHASE_ADVICE_FULL";
    String PURCHASE_ADVICE_PARTIAL = "PURCHASE_ADVICE_PARTIAL";
    String PURCHASE_ADVICE_MANUAL = "PURCHASE_ADVICE_MANUAL";
    String FINANCIAL_TRANSACTION = "FINANCIAL_TRANSACTION";
    String FALLBACK = "FALLBACK";
    String PRE_AUTHORISATION_COMPLETE = "PRE_AUTHORISATION_COMPLETE";
    String NO_OF_TXNS = "NO_OF_TXNS";
    String PURCHASE_WITH_NAQD = "PURCHASE_WITH_NAQD";
    String PURCHASE_WITH_NAQD_AR = "PURCHASE_WITH_NAQD_AR";
    String PURCHASE_NAQD = "PURCHASE_NAQD";

    String FINANCIAL_AUTHORIZATION = "FINANCIAL_AUTHORIZATION";


    //Transaction Mode's
    String MAGNETIC_STRIP = "MAGNETIC_STRIP";
    String EMV_CHIP = "EMV_CHIP";
    String CONTACT_LESS = "CONTACT_LESS";
    String MANUALLYENTER = "MANUALLYENTER";


    //Mapper Flow
    String MenuList = "menu_list";
    String MenuType = "menu_type";
    String TAG = "TAG";
    String TAG1 = "TAG1";
    String TAG2 = "TAG2";
    String TAG_FALLBACK = "TAG_FALLBACK";
    String DO_WAVE_AGAIN = "DO_WAVE_AGAIN";
    String TAG_CARD = "TAG_CARD";
    String TAG_CARD_MANUAL = "TAG_CARD_MANUAL";
    String TAG_REVERSAL = "TAG_REVERSAL";
    String TAG_STATUS = "TAG_STATUS";
    String TITLE = "title_toolbar";

    String Purchase_Amount = "Purchase_Amount";
    String Cashback_Amount = "Cashback Amount";
    String Total_Amount = "Total Amount";

    int Menu_Transaction = 0;
    int Menu_Merchant = 1;
    int Menu_Admin = 2;

    String TXT_Menu_Transaction = "";
    String TXT_Menu_Merchant = "";
    String TXT_Menu_Admin = "";

    String TXT_PURCHASE = "Purchase";
    String TXT_PURCHASE_CASHBACK = "Purchase Cashback";
    String TXT_PURCHASE_NAQD = "Purchase with NAQD";
    String TXT_PURCHASE_REVERSAL = "Reversal";
    String TXT_REFUND = "Refund";
    String TXT_CASH_ADVANCE = "Cash Advance";
    String TXT_PRE_AUTHORISATION = "Pre Authorisation";
    String TXT_PRE_AUTHORISATION_VOID = "Preauth Void";
    String TXT_PRE_AUTHORISATION_EXTENSION = "Preauth Extension";
    String TXT_PURCHASE_ADVICE = "Purchase Advice";

    //Merchant menu
    String DUPLICATE = "Duplicate";
    String RECONCILIATION = "Reconciliation";
    String SANPSHOT_TOTAL = "SANPSHOT_TOTAL";
    String RUNNING_TOTAL = "RUNNING_TOTAL";
    String RECONCILE_SETUP = "RECONCILE_SETUP";

    String HISTORY_VIEW = "HISTORY_VIEW";
    String LAST_EMV = "LAST_EMV";
    String CHANGE_PASSWORD = "CHANGE_PASSWORD";
    String TERMINFO_MENU = "TERMINFO_MENU";
    String SIM_NUMBER = "SIM_NUMBER";

    String DE_SAF_ALL_FILE = "DE_SAF_ALL_FILE";
    String SWITCH_CONNECTION = "SWITCH_CONNECTION";
    String SET_GPS_LOCATION = "SET_GPS_LOCATION";
    String SELECT_LANGUAGE = "SELECT_LANGUAGE";
    String MPORTAL_BATCH_UPLOAD = "MPORTAL_BATCH_UPLOAD";
    String USER_GUIDE_ = "USER_GUIDE_";


    //Admin Menu
    String REGISTRATION = "REGISTRATION";
    String SET_PARAMATERS = "SET_PARAMATERS";
    String EDIT_IP = "EDIT_IP";
    String FULL_DOWNLOAD = "FULL_DOWNLOAD";
    String PARTIAL_DOWNLOAD = "PARTIAL_DOWNLOAD";
    String SAF_VIEW = "SAF_VIEW";
    String DEL_SAF_FILE = "DEL_SAF_FILE";
    String TRSM_EDIT_FILE = "TRSM_RESET_FILE";
    String SET_DATE_TIME = "SET_DATE_TIME";
    String FORMAT_FILESYS = "FORMAT_FILESYS";
    String PRINT_TMS_DATA = "PRINT_TMS_DATA";
    String CHANGE_PASSWORD_ADMIN = "CHANGE_PASSWORD_ADMIN";
    String RESET_PASSWORD = "RESET_PASSWORD";
    String HOST_SETTING = "HOST_SETTING";
    String MANAGER_MENU = "MANAGER_MENU";
    String DEBUG_MODE = "DEBUG_MODE";
    String KEY_INJECTION = "KEY_INJECTION";
    String MERCHANT_PORTAL = "MERCHANT_PORTAL";

    // TMS Display TAG from Admin Menu
    String TMS_RETAILER_DATA = "TMS_RETAILER_DATA";
    String TMS_CARD_DATA = "TMS_CARD_DATA";
    String TMS_HOST_MSG_DATA = "TMS_HOST_MSG_DATA";
    String TMS_PUB_FEY_DATA = "TMS_PUB_FEY_DATA";
    String TMS_COMM_DATA = "TMS_COMM_DATA";
    String TMS_AID_LIST = "TMS_AID_LIST";
    String TMS_AID_DATA = "TMS_AID_DATA";
    String TMS_EXPORT_USB = "TMS_EXPORT_USB";
    String TMS_DEVICE_SPEC = "TMS_DEVICE_SPEC";

    // Set Parameters from Admin Menu
    String SPRM_PHONE_NUMBER = "SPRM_PHONE_NUMBER";
    String SPRM_VENDER_ID = "SPRM_VENDER_ID";
    String SPRM_TERMINAL_TYPE = "SPRM_TERMINAL_TYPE";
//    String SPRM_TERMINAL_SERIAL_NUM = "SPRM_TERMINAL_SERIAL_NUM";
    String SPRM_VENDOR_KEY1 = "SPRM_VENDOR_KEY1";
    String SPRM_SAMA_KEY1 = "SPRM_SAMA_KEY1";
    String SPRM_KEY_ISSUE_ = "SPRM_KEY_ISSUE_";
    String SPRM_TRSM_ID = "SPRM_TRSM_ID";
    String SPRM_NII_ID = "SPRM_NII_ID";
    String SPRM_TLS = "SPRM_TLS";
    String SPRM_IP_CONFIG = "SPRM_IP_CONFIG";
    String SPRM_PORT = "SPRM_PORT";

    // Host Settings Submenu from Admin Menu
    String HSTNG_CONNECTION_SETUP = "HSTNG_CONNECTION_SETUP";
    String HSTNG_PRIORITY = "HSTNG_PRIORITY";
    String HSTNG_PRIMARY_MENU = "HSTNG_PRIMARY_MENU";
    String HSTNG_SECONDARY_MENU = "HSTNG_SECONDARY_MENU";
    String HSTNG_TLS = "HSTNG_TLS";
    String HSTNG_GPRS_CONNECTED = "HSTNG_GPRS_CONNECTED";
    String HSTNG_GPRS_CONFG = "HSTNG_GPRS_CONFG";
    String HSTNG_WIFI_SETUP = "HSTNG_WIFI_SETUP";
    String HSTNG_GPRS_OPERATOR = "HSTNG_GPRS_OPERATOR";
    String HSTNG_DEBUG_OPTION = "HSTNG_DEBUG_OPTION";
    String HSTNG_PING_SETUP = "HSTNG_PING_SETUP";

    // Manager menu Submenu from Admin Menu
    String CHK_DIGIT_CALC = "CHK_DIGIT_CALC";
    String REMOTE_DOWNLOAD = "REMOTE_DOWNLOAD";

    // Reconsilation SETUP Submenu from Merchant Menu
    String CURRENT_STATUS = "CURRENT_STATUS";
    String RECONSILATION_TIME = "RECONSILATION_TIME";
    String ENABLE_DISABLE_RECON = "ENABLE_DISABLE_RECON";

    // TerminalMenu Submenu from Merchant Menu
    String TERMINAL_INFO = "TERMINAL_INFO";
    String PRINT_SYS_INFO = "PRINT_SYS_INFO";
    String TERMINAL_VENDER_PING = "TERMINAL_VENDER_PING";

    // Managermenu Submenu from Merchant Menu
    String TRANSACTION_VIEW = "TRANSACTION_VIEW";
    String RECONCILE_VIEW = "RECONCILE_VIEW";
    String SAF_HISTORY = "SAF_HISTORY";
    String DELETE_HISTORY = "DELETE_HISTORY";

    String UG_OPERATOR_TRANSACTION = "UG_OPERATOR_TRANSACTION";
    String UG_MERCHANT = "UG_MERCHANT";
    String UG_RRN = "UG_RRN";
    String UG_RESPONCE_CODE = "UG_RESPONCE_CODE";
    String UG_COMMON_ERROR_MSG = "UG_COMMON_ERROR_MSG";
    String UG_PAPER_ROLL_INSTALL = "UG_PAPER_ROLL_INSTALL";
    String UG_POWER_ON_OFF = "UG_POWER_ON_OFF";
    String UG_CARD_READER = "UG_CARD_READER";
    String UG_COMMON_TROUBLE_SHOOT = "UG_COMMON_TROUBLE_SHOOT";
    String UG_CAUTION_SAFETY = "UG_CAUTION_SAFETY";

    String UGO_PURCHASE = "UGO_PURCHASE";
    String UGO_PURCHASE_REVERSAL = "UGO_PURCHASE_REVERSAL";
    String UGO_REFUND = "UGO_REFUND";
    String UGO_CASH_ADVANCE = "UGO_CASH_ADVANCE";
    String UGO_PRE_AUTHORISATION = "UGO_PRE_AUTHORISATION";
    String UGO_PURCHASE_ADVICE_PARTIAL = "UGO_PURCHASE_ADVICE_PARTIAL";
    String UGO_PURCHASE_NAQD = "UGO_PURCHASE_NAQD";


    String UGO_MODE_CHIP_CARD = "UGO_MODE_CHIP_CARD";
    String UGO_MODE_MAGNETIC_STRIPE = "UGO_MODE_MAGNETIC_STRIPE";
    String UGO_MODE_CONACTLESS = "UGO_MODE_CONACTLESS";
    String UGO_MODE_MANUAL_ENTRY = "UGO_MODE_MANUAL_ENTRY";

    //receipt Types
    String RECEIPT_TYPE_RECONCILIATION = "RECONCILIATION";

    //card schemes
    String CARD_SCHEME_MADA = "MADA";
    String CARD_SCHEME_GCCNET = "GCCNET";
    String CARD_SCHEME_MASTER_CARD = "MASTERCARD";
    String CARD_SCHEME_MAESTRO = "MAESTRO";
    String CARD_SCHEME_VISA = "VISA";
    String CARD_SCHEME_AMERICAN_EXPRESS = "AMERICAN EXPRESS";
    String CARD_SCHEME_UNION_PAY = "UNION PAY";

//visa
    String A0000000031010 = "A0000000031010";
    String A0000000032010 = "A0000000032010";
    //master
    String A0000000041010 = "A0000000041010";
    //maestro
    String A0000000043060 = "A0000000043060";
    //mada
    String A0000002281010 = "A0000002281010";
    String A0000002282010 = "A0000002282010";
    //union pay
    String A000000333010101 = "A000000333010101";
    String A000000333010102 = "A000000333010102";

    //American Express
    String A00000002501 = "A00000002501";


    //success response
    String SUCCESS_RESPONSE_000 = "000";
    String SUCCESS_RESPONSE_001 = "001";
    String SUCCESS_RESPONSE_003 = "003";
    String SUCCESS_RESPONSE_007 = "007";
    String SUCCESS_RESPONSE_800 = "800";
    String REVERSAL_RESPONSE_400 = "400";


//check online offline
    String APP_CRYPTOGRAM_ARQC = "ONLINE";  //online
    String APP_CRYPTOGRAM_TC = "OFFLINE";    //offline
    String APP_CRYPTOGRAM_AAC = "DECLINE";   //decline

    String CVM_ONLINE_PIN_VALUE = "420000";
    String CVM_NO = "1F0000";
    String CVM_FAIL = "1F0001";
    String CVM_SIGNATURE = "1E0000";


    String SAF_APPROVED = "087";
    String SAF_APPROVED_UNABLE = "089";
    String SAF_REJECTED = "190";
    String SAF_DECLINED = "188";
    String SAF_REFUND = "000";

    String MERCHANT_IP_CONFIG = "MERCHANT_IP_CONFIG";
    String MERCHANT_PORT = "MERCHANT_PORT";

}
